### POST request to example server
POST http://localhost:8080/api/login
Content-Type: application/json;charset=UTF-8

{
  "username": "이순신",
  "password": "1234"
}

### GET request to example server
GET http://localhost:8080/api/admin/get
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLsnbTsiJzsi6AiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTcyNDc1NTQ4MiwiaWF0IjoxNzI0NzUxODgyfQ.Yx91OK03dRctpCs3JMHV4lQv41BB0aIidFK4SJZfX2g
