### POST request to example server
POST http://localhost:8080/api/login
Content-Type: application/json;charset=UTF-8
Authorization:

{
  "username": "이순신",
  "password": "1234"
}

### GET request to example server
GET http://localhost:8080/api/user
Content-Type: application/json;charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLsnbTsiJzsi6AiLCJhdXRoIjoiVVNFUiIsImV4cCI6MTcyNDYwNzg5MCwiaWF0IjoxNzI0NjA0MjkwfQ.TR9DzyF6kb50oNFlVpD-YfaA-OECKAJGEM5Jg8IJJcc

